#!/usr/bin/env sh

# Function to count and remove files
remove_files() {
  local pattern="$1"
  local count=$(find . -type f -name "$pattern" | wc -l)
  find . -type f -name "$pattern" -delete
  echo "Removed $count files matching $pattern"
}

# Remove auxiliary files generated by LaTeX recursively
remove_files "*.aux"
remove_files "*.log"
remove_files "*.out"
remove_files "*.toc"
remove_files "*.lof"
remove_files "*.lot"
remove_files "*.bbl"
remove_files "*.blg"
remove_files "*.brf"
remove_files "*.fls"
remove_files "*.fdb_latexmk"
remove_files "*.synctex.gz"
remove_files "*.xdv"
remove_files "*.nav"
remove_files "*.snm"
remove_files "*.vrb"
remove_files "*.run.xml"
remove_files "*.bcf"

# Remove temporary files
remove_files "*~"

echo "Cleanup complete!"
